### ISSUE TITLE
iCal sensor not showing up in UI

### ISSUE THREAD

**Issue by JeroenTuinstra** [tybritten/ical-sensor-homeassistant#107]
Installed i-cal sensor through HACS. It is not showing up in integration of Home Assistant:  2022.8.7

I see the custom_components/ical directory is made. HACS reports it as installed. Yet HA integrations doesn't see it. 

What to do? 

Log file only says the following: 

``` 2022-09-05 20:20:34.568 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ical which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant ```

**Comment by marcinprzybysz86** [comment]
Same for me. First time using. Installed via HACS, cannot be found in HA integrations (2022.9.1)

**Comment by Olen** [comment]
Maybe the same issue as this? 

https://github.com/tybritten/ical-sensor-homeassistant/issues/88#issuecomment-1097752839

**Comment by JeroenTuinstra** [comment]
It turns out it just takes time. You have to wait, it will show up eventually.
