### ISSUE TITLE
iCal uses old icalendar package

### ISSUE THREAD

**Issue by jmgiaever** [tybritten/ical-sensor-homeassistant#114]
iCal uses old icalendar package (4.0.7) which breaks with the required icalendar==5.0.4 of Home Assistant (2023.2.5)

**Comment by Olen** [comment]
I created a very quick PR. https://github.com/tybritten/ical-sensor-homeassistant/pull/115
I have not tested it, but please check it out and let us know of any issues.

**Comment by jmgiaever** [comment]
Works great here too.

**Comment by Olen** [comment]
@tybritten Would you consider merging #115 and pushing a new release?

**Comment by tybritten** [comment]
Done. 1.6.5
