### ISSUE TITLE
Location missing from calendar entity

### ISSUE THREAD

**Issue by phillprice** [tybritten/ical-sensor-homeassistant#116]
Since the update 1.6.5 the calendar entity is not showing the location. The location is present in the sensor entities

Example (I've hand obfuscated details)
![23583C45-4CED-4356-B17F-57EB535C2A4C](https://user-images.githubusercontent.com/320214/223405534-fcc34112-c2f2-4f98-a1a4-d87ee30681f3.png)

**Comment by Cybersmurfen** [comment]
This is solved in my PRs from today

**Comment by tybritten** [comment]
Ok I'll look at those PRs now..next time can you put both changes in one PR?

**Comment by tybritten** [comment]
Released in https://github.com/tybritten/ical-sensor-homeassistant/releases/tag/1.6.6
