### ISSUE TITLE
iCal uses old version of icalendar that conflicts with HA

### ISSUE THREAD

**Issue by jmgiaever** [tybritten/ical-sensor-homeassistant#120]
iCal uses old icalendar package (5.0.4) which breaks with the required icalendar==5.0.5 of Home Assistant (2023.4.6)

**Comment by Reiqu** [comment]
In HA 2023.6.0 it is not working anymore. 

In logs I got the following line: 
`homeassistant.requirements.RequirementsNotFound: Requirements for ical not found: ['icalendar==5.0.4'].`

**Comment by jmgiaever** [comment]
You can probably make a hack for it yourself by editing the manifest.json file in the custom_component folder, and match the version number to whatever version is required by HA Core.

**Comment by tbrasser** [comment]
I changed the == to >= and now both ical sensor & local todo work :)
