### ISSUE TITLE
Does not show current day only future events

### ISSUE THREAD

**Issue by MajorAutomation** [tybritten/ical-sensor-homeassistant#123]
Howdy,
Love this plugin, but it doesn't show items from today, is there a line of code I can change to display today as well as sensor 0?
Thanks
MaJor

**Comment by peterthorvald** [comment]
I have the same issue. Did you ever solve it?

**Comment by MajorAutomation** [comment]
> I have the same issue. Did you ever solve it?

No, no one ever got back to me, it actually makes the plugin useless as why the hell wouldn't you want today's listed?

**Comment by peterthorvald** [comment]
I think this might be the source of my issue at least https://github.com/tybritten/ical-sensor-homeassistant/issues/54

**Comment by tybritten** [comment]
I'll take a look at this today

**Comment by tybritten** [comment]
fixed in https://github.com/tybritten/ical-sensor-homeassistant/pull/127

**Comment by PapaMater** [comment]
This issue does not appear to be fixed for me and there is no mention to this issue or #127 in the lates release.  Using 3.1.8.

Is is necessary to remove historical events? Calendars are helpful reminders for future events, but are equally as useful for recalling previous events.

**Comment by tybritten** [comment]
Yes, if you look at #127 you'll see it hasn't been merged yet, so it won't be fixed for you yet.

**Comment by tybritten** [comment]
Fix Release: https://github.com/tybritten/ical-sensor-homeassistant/releases/tag/1.6.7

**Comment by Olen** [comment]
A beta release that should address this is now available: [v1.10.0b1](https://github.com/tybritten/ical-sensor-homeassistant/releases/tag/v1.10.0b1)

The midnight end-time filter was incorrectly dropping all-day events on their own day, which could cause today's events to be skipped. This has been fixed.

To test: in HACS, enable "Show beta versions" in the download dialog and select `v1.10.0b1`. Feedback welcome.
