### ISSUE TITLE
iCal Sensor addin does not really work anymore on 2023.10.1b2

### ISSUE THREAD

**Issue by dreimer1986** [tybritten/ical-sensor-homeassistant#130]
Upcoming HA version seems to cause some problems with this addin here. All my sensors for my calendars are gone. Log is completely empty though. I would expect at least one warning or error here in default

![image](https://github.com/tybritten/ical-sensor-homeassistant/assets/29841368/32823952-c036-4ba3-b514-ee607bef0259)

[home-assistant_ical_2023-09-29T08-41-55.951Z.log](https://github.com/tybritten/ical-sensor-homeassistant/files/12762708/home-assistant_ical_2023-09-29T08-41-55.951Z.log)

**Comment by woodmj74** [comment]
Are your sensors gone or just not visible on this screen? Mine still exist and work (sensor.ical_xxx) just not visible here - I don't remember last time I saw them here.
2023.10.0b2

**Comment by dreimer1986** [comment]
OK, nvm... They were GONE completely, but now are back after a reboot or two. And yes, they are not seen in there, but are available ^^ Sry for the mess.

**Comment by JokerGermany** [comment]
Thats already in 2023.9 the case.
In was confused as hell, too...
