### ISSUE TITLE
Depreaction warning

### ISSUE THREAD

**Issue by aslak3** [tybritten/ical-sensor-homeassistant#141]
HA 2024.8.3

`
Detected code that calls async_forward_entry_setup for integration ical with title: Our house and entry_id: 528f866a508f2c56a2c2b24de0df8a52, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
`

**Comment by aslak3** [comment]
This looks like a slightly different wording of the warning described in #140. The date it needs to be fixed by is six months earlier now though....

**Comment by tybritten** [comment]
Fixed in https://github.com/tybritten/ical-sensor-homeassistant/pull/139

**Comment by Olen** [comment]
A beta release that removes all deprecated APIs is now available: [v1.10.0b1](https://github.com/tybritten/ical-sensor-homeassistant/releases/tag/v1.10.0b1)

`async_forward_entry_setup` has been replaced with `async_forward_entry_setups`, and `async_forward_entry_unload` replaced with `async_unload_platforms`.

To test: in HACS, enable "Show beta versions" in the download dialog and select `v1.10.0b1`. Feedback welcome.
