### ISSUE TITLE
1.7.0 Sensor Names Changed

### ISSUE THREAD

**Issue by woodmj74** [tybritten/ical-sensor-homeassistant#146]
Prior to version 1.7.0 the specified number of sensors were called:

`sensor.ical_[calendar]_event_[num]`

Since installing v1.7.0 I have a duplicate in the ical in the sensor name:

`sensor.ical_ical_[calendar]_event_[num]`

I have reloaded the code, added a new calendar to check  which also got the duplicate ical name:

![image](https://github.com/user-attachments/assets/fd1df2c4-991c-4ef6-8aad-80de7091347a)

**Comment by tybritten** [comment]
Checking now

**Comment by tybritten** [comment]
FYI @N3rdix

**Comment by N3rdix** [comment]
Thanks for the fix, forgot that the domain is not needed for a unique ID 😆

**Comment by tybritten** [comment]
No worries, thanks for the PR and I missed it too.
