### ISSUE TITLE
How to change timezone

### ISSUE THREAD

**Issue by mar005** [tybritten/ical-sensor-homeassistant#16]
I am in seeing that the UTC timecode are wrong. I see this timezone in the start time for an event, for example, start: 2019-09-07T15:30:00-04:00 this means that UTC time is 15:30 and -4hrs. Yet I am in CST which should have 5 instead of 4. I notice that all the times that are set in the state are 1hr ahead of my TZ. Is this modifiable?

**Comment by oechslein** [comment]
As far as I understood the code, it extracts only the date without the time zone information from the ical source. I guess instead of:
`arrow.get(event['DTSTART'].dt)`
it should be 
`arrow.get(event['DTSTART'].dt, event['DTSTART'].params.get('TZID'))`

**Comment by Olen** [comment]
I am not 100% sure, but to me it looks like the DTSTART should containt an offset, and that is used, and the displayed time is shown as the local time you set on the home-assistant server.
But be aware of issues with summer time and how your server treats that.

Check what is set as timezone on the server HA is running at.

**Comment by mar005** [comment]
I ended up just using string manipulations using javascript to correct the issues i found with this timestamp. I found out it was based on eastern timezone. Would be nice, if you could add a TZ.

**Comment by oechslein** [comment]
@mar005 Do you mind sharing some examples from your caldav source?

**Comment by mar005** [comment]
http://api.calreply.net/webcal/1decfcd2-46bb-435f-ac36-c35c4bc5c013

Sorry this took me so long.
