### ISSUE TITLE
macOS 10.15 Calendar

### ISSUE THREAD

**Issue by haakonstorm** [tybritten/ical-sensor-homeassistant#24]
Hey! Testing out the `ical` integration 

- when I create and share a Calendar with `calendar.app` from ´macos 10.15 catalina`, I get a link like `webcal://p31-caldav.icloud.com/published/2/ODg3MzYwMTY4ODczNjAxNvEb6BxHp_EwfT8xPuCo2KePwfb0esszVX62STeuIWy280sMD7Nf_x3m7CkFdtlgLd83BMgrC8R5C3W7EGjh`
- protocol is `webcal:` but ical requires `http:`
` tips? I tried replacing `webcal` with `http` but no go

**Comment by Olen** [comment]
Have your tried accessing the url directly in a browser (replacing webcal:// with http://)
Also, from the hostname, it _looks_ like you might be sharing a caldav link, not an ical-link.
But I am not familiar with the mac-universe, so it might just be a misleading URL.
