### ISSUE TITLE
Convert to home assistant calendar component?

### ISSUE THREAD

**Issue by andersonshatch** [tybritten/ical-sensor-homeassistant#25]
Is it possible to convert this or make it compatible with the built-in calendar component that HASS has now? If it adopted that, it would be equivalent to the caldav/google calendar integrations, and work with the [Lovelace Calendar Card](https://github.com/ljmerza/calendar-card) for example.

**Comment by Olen** [comment]
Might be a good idea, but unless I am wrong, this will be a breaking change.
One of the reasons I like this component is that it is easy to use the events-sensors in scripts and automations.

But we might be able to do both - add a calendar component next to the current sensors, so we don't break current setups.
