### ISSUE TITLE
Czech characters not displayed correctly

### ISSUE THREAD

**Issue by scstraus** [tybritten/ical-sensor-homeassistant#27]
Hi, I'm trying to use this component on this feed:
http://www.mozilla.org/media/caldata/CzechHolidays.ics

But instead of correctly displaying the holiday name as:

Velký pátek

It's displayed as:

VelkÃ½ pÃ¡tek 

Another example is:

Velikonoční pondělí

Which is displayed as

VelikonoÄnÃ­ pondÄlÃ

I'm guessing it's just using ACSII instead of Unicode? Could Unicode support be added?

**Comment by Olen** [comment]
Please test the latest version.  I have no issues with Norwegian characters at least in my calendars.

**Comment by scstraus** [comment]
I managed to find an English version of the Czech holidays feed so we can call it fixed if it works for you.
