### ISSUE TITLE
Feature request: option to remove year and hour in sensor

### ISSUE THREAD

**Issue by scstraus** [tybritten/ical-sensor-homeassistant#28]
Hi, I made a little holiday sensor with this and it works really nicely, but showing it on my dashboard it contains a too bit much information. 
![image](https://user-images.githubusercontent.com/7644023/78450553-ac306b80-767f-11ea-9edc-91e2cc7c604a.png)

Would it be possible to have some options to decide which part of the data ends up in the sensor value? I'd like to remove the year and hour to make it more concise.

**Comment by Olen** [comment]
The new version has attributes "Summary" and "Friendly Name" without date and timestamps.  You can create your own template to your liking by combining these with the start and end attributes.

**Comment by scstraus** [comment]
Thanks. I ended up making some very complex templates which produced some very nice sensors for display. Maybe you can take some inspiration from them:
https://github.com/scstraus/home-assistant-config/blob/master/sensors/other_template_sensors.yaml#L361-L654
