### ISSUE TITLE
Mimic exposed sensors of the CalDav integration

### ISSUE THREAD

**Issue by cromulus** [tybritten/ical-sensor-homeassistant#32]
Hi!
Thanks for creating this!

A thought: perhaps it might make sense to expose the same sorts of sensors that the [CalDav](https://www.home-assistant.io/integrations/caldav/) integration does? 

This way they could be drop in compatible with each other.

Additionally, the sorts of things I would like to automate from a ical feed are current and upcoming meetings.

Thanks!

**Comment by Olen** [comment]
I have more or less completely rewritten the addon, and consider pushing it as a new integration.

https://github.com/Olen/home-assistant/tree/ical/homeassistant/components/ical

This uses config flow (GUI) to add and remove calendars, and provides both a calendar object (same as the google calendar or caldav integrations do), and the event-sensors that this integration provides.

In other words, you can both use the calendar cards, and/or sensors to provide a list of upcoming events:

![image](https://user-images.githubusercontent.com/203184/96702272-e3533980-1391-11eb-9147-3f6c98d69e45.png)

**Comment by henrikhjelm** [comment]
you most do the info page about it and join hacs discord -> https://discord.gg/apgchf8

**Comment by Olen** [comment]
I am not sure if this should be added to hacs or to core.
In the mean time, I have updated the custom_component in my repo to reflect the changes I did to get config flow up and running:
https://github.com/Olen/ical-sensor-homeassistant

This version also has improved handling of timezone issues and events that cross daylight savings time start/end.

**Comment by Olen** [comment]
Pretty sure this was fixed after the merge of my changes into this repo.
Please verify by upgrading to the latest version

**Comment by Olen** [comment]
Closing this as the feature was added
