### ISSUE TITLE
Integration Flow : {"message": "Invalid handler specified"}

### ISSUE THREAD

**Issue by navet** [tybritten/ical-sensor-homeassistant#37]
Version 1.2
HA core-2021.1.4
supervisor-2021.01.4

Fresh install using HACs. 
When selecting ICAL in integration the flow does not kick in. All other flows in integrations seem to work fine.

Header
`Request URL: http://hassio.local:8123/api/config/config_entries/flow
Request Method: POST
Status Code: 404 Not Found
Remote Address: 10.1.1.100:8123
Referrer Policy: same-origin

Content-Encoding: deflate
Content-Length: 48
Content-Type: application/json
Date: Sun, 17 Jan 2021 19:44:34 GMT
Server: Python/3.8 aiohttp/3.7.3

Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmNzFmN2ViNmM3NmE0MDIxYTZjNGY4ZGFjZWU2MWM2NyIsImlhdCI6MTYxMDkxMDkyOCwiZXhwIjoxNjEwOTEyNzI4fQ.a1cJE6XTY43vmH-uO-FalWTkh5u_G2MNc6GQg8XG-tc
Connection: keep-alive
Content-Length: 46
Content-Type: application/json;charset=UTF-8
DNT: 1
HA-Frontend-Base: http://hassio.local:8123
Host: hassio.local:8123
Origin: http://hassio.local:8123
Referer: http://hassio.local:8123/config/integrations
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75

{handler: "ics", show_advanced_options: true}
handler: "ics"
show_advanced_options: true`

Response
`{"message": "Invalid handler specified"}`

**Comment by tybritten** [comment]
Ah I think I see the issue. Upgrade to 1.3

**Comment by navet** [comment]
That fixed it. Thanks
