### ISSUE TITLE
Exception can't compare offset-naive and offset-aware datetimes in starts/ends

### ISSUE THREAD

**Issue by henrikhjelm** [tybritten/ical-sensor-homeassistant#38]
Exception can't compare offset-naive and offset-aware datetimes in starts/ends: XXXXXXXXXXX - Start: 2020-07-03 12:05:00+02:00 - End: 2020-07-03 13:25:00+02:00, RRule: vRecur({'FREQ': ['WEEKLY'], 'BYDAY': ['FR']})

**Comment by Olen** [comment]
I was certain I had found and fixed all of those...

Can you sow the original vevent? (Just remove the descriptions and locations etc).

**Comment by henrikhjelm** [comment]
BEGIN:VEVENT
DTSTAMP:20210119T142152Z
DTSTART;TZID=Europe/Stockholm:20200629T101000
DTEND;TZID=Europe/Stockholm:20200629T113000
SUMMARY: XXXXX
DESCRIPTION:Måndag 10:10-11:30 XXXXXXX
RRULE:FREQ=WEEKLY;BYDAY=MO
EXDATE:20210104T101000,20210118T101000,20210125T101000,20210201T101000,2021
 0208T101000,20210215T101000,20210222T101000,20210301T101000,20210308T10100
 0,20210315T101000,20210322T101000,20210329T101000,20210405T101000,20210412
 T101000,20210419T101000,20210426T101000,20210503T101000,20210510T101000,20
 210517T101000,20210524T101000,20210531T101000,20210607T101000,20210614T101
 000,20210621T101000,20210628T101000,20200629T101000,20200706T101000,202007
 13T101000,20200720T101000,20200727T101000,20200803T101000,20200810T101000,
 20200817T101000,20201012T101000,20201026T101000,20201109T101000,20201228T1
 01000
UID:lesson-252322-0
TZID:Europe/Stockholm
END:VEVENT

**Comment by Olen** [comment]
Ah, I guess it's the exdates. I did not have any events with those...
I'll have a look.

**Comment by Olen** [comment]
Do you have any more log output as well?
Or even better, if you are able to add debug-logging to the component:

```
logger:
  logs:
    custom_components.ical: debug

```

**Comment by henrikhjelm** [comment]
discord : Henrik#3336 ?

**Comment by Olen** [comment]
There is something going on here, and I have not been able to pinpoint it yet.
I get an error in some of my calendars as well, which does not make sense.

Exception RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware in start_rules.rrule: Xxxxxxx - Start: 2021-01-26 13:00:00 - RRule: vRecur({'FREQ': ['WEEKLY'], 'UNTIL': [datetime.datetime(2022, 1, 18, 12, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC'))], 'INTERVAL': [1], 'BYDAY': ['TU'], 'WKST': ['MO']})
 

The "Until" here clearly has a UTC timestamp, so I don't understand what it complains about.
But it could be an upstream problem.  I'll investigate further in a few days

**Comment by Grimidor** [comment]
I have this error too.

**iCal Version**
   1.4 according to HACS
   1.3 according to manifest.json

**Error message**
Exception can't compare offset-naive and offset-aware datetimes in starts/ends: Lunch - Start: 2021-07-06 11:15:00+02:00 - End: 2021-07-06 11:45:00+02:00, RRule: vRecur({'FREQ': ['WEEKLY'], 'BYDAY': ['TU']})

**iCal EVENT**
BEGIN:VEVENT
DTSTAMP:20210906T101624Z
DTSTART;TZID=Europe/Stockholm:20210706T111500
DTEND;TZID=Europe/Stockholm:20210706T114500
SUMMARY:Lunch
DESCRIPTION:Tisdag 11:15-11:45 Lunch 
RRULE:FREQ=WEEKLY;BYDAY=TU
EXDATE:20220104T111500,20220222T111500,20220308T111500,20220412T111500,2022
 0510T111500,20220614T111500,20220621T111500,20220628T111500,20210706T11150
 0,20210713T111500,20210720T111500,20210727T111500,20210803T111500,20210810
 T111500,20210817T111500,20211102T111500,20211228T111500,20220104T111500
UID:lesson-46160-1
TZID:Europe/Stockholm
END:VEVENT
