### ISSUE TITLE
ETA will always be "0"

### ISSUE THREAD

**Issue by Schrolli91** [tybritten/ical-sensor-homeassistant#39]
Have installed the newset (1.3) version and discoverd, that all ETAs are "0".
Any ideas whats going wrong here?

![image](https://user-images.githubusercontent.com/6043382/104959170-e0d4a000-59d1-11eb-8a24-02c8fa996b41.png)

**Comment by Schrolli91** [comment]
If i remove the time ``...T08:00:00+01:00` it will work. Is this a bug in the parser?

**Comment by tybritten** [comment]
can you share the source ical event?

**Comment by Olen** [comment]
Works fine here.  Just updated to 1.3 from HACS and reloaded and it stille shows the correct number of days.

```
summary: XXXX
description: 
location: 
start: 2021-01-25T08:00:00+01:00
end: 2021-01-25T09:00:00+01:00
eta: 6
all_day: false
icon: mdi:calendar
```

**Comment by tybritten** [comment]
Same. I'm assuming an issue in the source format

**Comment by Schrolli91** [comment]
Here i have one Event from my calendar:
```
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20210201T080000
DTEND;TZID=Europe/Berlin:20210201T090000
TRANSP:TRANSPARENT
LOCATION;LANGUAGE=de:#############
UID:1611077476014-1@################
DTSTAMP:20210119T063116Z
DESCRIPTION;LANGUAGE=de:#############
SUMMARY;LANGUAGE=de:#################
PRIORITY:9
CLASS:PUBLIC
STATUS:CONFIRMED
END:VEVENT
```

**Comment by Olen** [comment]
And you are sure that one has ETA=0?

The other event you made a screenshot of is from the same date as the case was created, so it is correct that that one is 0.

**Comment by Schrolli91** [comment]
Ohhh you're right... now im confused - i will try it again and look for a futre event and check that behavior again...

**Comment by Schrolli91** [comment]
You were right - all my ETAs are correct! (when i dont look at a event where the ETA has to be 0 at this day :-D )
Sorry for wasting your time ... And thanks for your efforts.
