### ISSUE TITLE
Nowhere to enter the Calendar Name and URL from the UI.

### ISSUE THREAD

**Issue by aasquith94** [tybritten/ical-sensor-homeassistant#45]
Maybe im missing something maybe im dumb. but seems like a bug as it seems to install fine but theres no way through the UI to add a url and name of the calendar.

**Comment by tybritten** [comment]
Did you go to Configuration>Integrations>Add Integration and select iCal?

**Comment by aasquith94** [comment]
Yes i had. even after a few restarts it wasn't showing, 24 hours later it finally appeared in integrations.
