### ISSUE TITLE
Version key

### ISSUE THREAD

**Issue by dodg3r** [tybritten/ical-sensor-homeassistant#46]
This shows in log:

`WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'ical'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'ical'`

**Comment by tybritten** [comment]
Thanks, will fix

**Comment by tybritten** [comment]
just checked, we do have that in there. What version are you running? How did you install?

**Comment by dodg3r** [comment]
Strange. I'm installing through hacs.

**Comment by dodg3r** [comment]
Hi again. 

I've copied all of the files to custom folder and now it works without the version error. It must be my misstake

**Comment by baloba52** [comment]
Hi.

Why doesnt hacs have the latest version?
