### ISSUE TITLE
iPhone Calendar URL

### ISSUE THREAD

**Issue by NickSutton** [tybritten/ical-sensor-homeassistant#49]
Hi,

I followed this guide to find the URL for the component settings: https://www.techrepublic.com/article/how-to-find-your-icloud-calendar-url/

But was asked for log in information. Is there anywhere this can be entered to link my iCloud calendar with this module?

Thanks,

**Comment by tybritten** [comment]
duplicate of https://github.com/tybritten/ical-sensor-homeassistant/issues/78
