### ISSUE TITLE
integration doesnt appear on configuration->integration

### ISSUE THREAD

**Issue by clyra** [tybritten/ical-sensor-homeassistant#53]
Hi,

I'm running HA 2021.5.5 on docker and just installed the ical sensor using hacs. The integration seem to be installed, but trying to add/configure it using the configuration -> integrations -> add integration doest not work as it's not listed on the "set up new integration menu". The following images shows the problem:

![Screen Shot 2021-05-25 at 13 10 18](https://user-images.githubusercontent.com/4778266/119532999-cdf52200-bd5b-11eb-85c1-e6a99e64497c.png)

![Screen Shot 2021-05-25 at 13 09 59](https://user-images.githubusercontent.com/4778266/119533043-d6e5f380-bd5b-11eb-91b8-45df9890f812.png)

**Comment by CoherentLogic** [comment]
I'm having the same exact issue. Multiple HA restarts have no effect.

**Comment by clyra** [comment]
The funny thing is that I tried it on my HA "dev" instance first and it didnt worked. So I tried it again on my "production" HA and it worked!! My "dev" instance has a minimal configuration so I can reload it faster. I'm wondering that perhaps there's a package needed by ical that was installed by another integration on my production HA that isnt present on the dev.

**Comment by tybritten** [comment]
That's odd. It showed up fine in the list for me just now. How did you install it? HACS?

**Comment by clyra** [comment]
yes, hacs. But I also tried by copying the files to custom_components.

**Comment by CoherentLogic** [comment]
Updating HACS and doing one more restart fixed it for me.

**Comment by clyra** [comment]
hm... that's right. Going from 1.12.3 to 1.12.4 (HACS) seems to solve the problem. thx.
