### ISSUE TITLE
Duplicate sensors for the same event

### ISSUE THREAD

**Issue by scstraus** [tybritten/ical-sensor-homeassistant#55]
Hi there. Somehow I'm getting 2 sensors showing for the exact same event on the same date, and one of them has the wrong ETA. iCal component is installed via HACS and configured via the integrations GUI. Running latest version. Here are the states of my sensors (have been wrong for days).

![ical_problem](https://user-images.githubusercontent.com/7644023/123152923-6c60ca00-d465-11eb-96d7-cd0e52aa05a3.png)

Logs are [here](https://www.dropbox.com/s/po7kydzptixjr0g/ical-problem.log?dl=0)

**Comment by Olen** [comment]
Hmm..  This could be that since you have no "event_4" which should have taken "event_3"s place.  The old "event_3" was stuck when it was "promoted" to event_2.
I have never had a calendar with so few events, so this might have been missed.  We will look into it.

**Comment by scstraus** [comment]
Thank you. Will reopen if this happens again.
