### ISSUE TITLE
Struggling Google Calendar integration

### ISSUE THREAD

**Issue by Humb3l** [tybritten/ical-sensor-homeassistant#85]
Maybe I'm too stupid, but actually I can't get this to work right now.
I'm trying to integrate this plugin to get the next event from my google calender. But everything I try fails. Currently I integrated the Google Calendar with the native Home Assistant Integration into my Home Assistant. 

What I tried:

Name: calendar.my-calendar
URL: localhost:8123/api/calendars

Name: my-calendar
URL: original url to my google calendar

Name: my-calendar
URL: localhost:8123/api/calendars

Name: calendar.my-calendar
URL: /api/calendars

Could this be an authentication problem? 

## System Health

version | core-2022.4.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.32-v8+
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4727
Installed Version | 1.24.3
Stage | running
Available Repositories | 1080
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

**Comment by Olen** [comment]
Not sure what you are trying to do here.
This integration is for subscribing to calendars in ical format.

To get the ical-url of your Google calendar, you can look at this link:
https://support.google.com/calendar/answer/37648?hl=en

**Comment by Humb3l** [comment]
Like I said, I'm stupid :D. Thanks so much that worked :). Maybe worth integrating this hint in the documentation
