### ISSUE TITLE
Can't install ical

### ISSUE THREAD

**Issue by mariusvanderwerff** [tybritten/ical-sensor-homeassistant#94]
Hi there,

I installed ical by HACS and the files are in the right place, but after a restart I tried to add ical as a integration but without succes.
Am I doing something worng?

**Comment by genem2** [comment]
Well, just came across this component today, and am also not sure what's happening.
Installed via HACS, all looks good, and during a restarted, HA sees it:

`2022-08-04 07:30:38.625 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ical which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
`

But: Settings | Integrations | Add Integration: It's not in the list.
Nothing reported with:
` docker exec homeassistant python -m homeassistant --script check_config --config /config`

Thanks...

## System Information

version | core-2022.8.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.46-Unraid
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4736
Installed Version | 1.26.2
Stage | running
Available Repositories | 1084
Downloaded Repositories | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 24
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 21, 2022, 4:35 PM
-- | --
current_recorder_run | August 4, 2022, 7:30 AM
estimated_db_size | 68.79 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.1.0 (3871c0b)
-- | --
cloud_online | 6 / 7
local_online | 6 / 6

</details>

**Comment by Shizool-arch** [comment]
HI same problem here.

Home Assistant 2022.8.0
Supervisor 2022.07.0
Operating System 8.4
Interfejs użytkownika: 20220802.0 - latest

**Comment by genem2** [comment]
FWIW: After a few hours working other functionally, and several HA restarts, I accidentally noticed ical eventually appeared in the Integrations list.  It's been working great since then...

**Comment by brixharlem** [comment]
Same problem here. iCal does not appear in the UI. 
I tried HACS and manual install.
